
import React from 'react'
import ProfileComponent from './component'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "UMS/Profile",
  description: "Generated by create next app",
};

function ProfilePage() {
  return (
    <ProfileComponent />
  )
}

export default ProfilePage