
import React from 'react'

import { Metadata } from 'next';
import LoginComponent from '@/components/login/LoginPage';

export const metadata: Metadata = {
  title: "UMS/Login",
  description: "Generated by create next app",
};

const LoginPage = () => {

  
  return(
    <LoginComponent />
  )
};

export default LoginPage;
