import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const RootLayout=({ children}: Readonly<{children: React.ReactNode;}>)=> {
 const RootLayout=({ children}: React.PropsWithChildren)=> {
  return (
    
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <AntdRegistry>
            <Providers>
              {children}
            </Providers>
          </AntdRegistry>
        </body>
      </html>
    
  );
}

export default RootLayout